### ISSUE TITLE
Operator - Move the target

### ISSUE THREAD

**Issue by jackjackrene** [jackjackrene/SAD_Pi#6]
As an Operator I want to move the target on the screen because I want to aim at the targets in play. to Operator - Move the target

**Comment by jadmr** [comment]
Are you referring to manually aiming at the target? While its possible to implement this feature in the command line interface (Menu: move left, move up, move down, etc), it wouldn't be practical because the command line wouldn't be able to give some form of reference as to where the missile is going to land (on the GUI, a crosshair overlay of the video feed would kinda make sense).

**Comment by thomasericdean** [comment]
This user story was moved to Milestone #3 based on the above comment by Jorge

**Comment by thomasericdean** [comment]
Not applicable
